#!/usr/bin/env zsh

SSH_REPO_URL="git@github.com:BenGu3/dotfiles.git"

#-----------------------------------------
# Install Homebrew/packages
#-----------------------------------------

if ! command -v brew >/dev/null 2>&1; then
  echo "➡️ Installing homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f "$HOME/.Brewfile" ]; then
  echo "➡️ Installing brew packages..."
  brew bundle --global
fi

#-----------------------------------------
# Create common directores
#-----------------------------------------

if [ ! -d "$HOME/repos/work" ]; then
  echo "➡️ Creating work repos directory..."
  mkdir -p $HOME/repos/work
fi

if [ ! -d "$HOME/repos/personal" ]; then
  echo "➡️ Creating personal repos directory..."
  mkdir -p $HOME/repos/personal
fi

#-----------------------------------------
# Install oh-my-zsh
#-----------------------------------------

if [ ! -d "$HOME/.oh-my-zsh" ]; then
  echo "➡️ Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

source "$HOME/.zshrc"

#-----------------------------------------
# Install spaceship theme
#-----------------------------------------

if [ ! -d "$ZSH_CUSTOM/themes/spaceship-prompt" ]; then
  echo "➡️ Installing spaceship theme..."
  git clone https://github.com/spaceship-prompt/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt" --depth=1
  ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
fi

#-----------------------------------------
# Install fzf-tab
#-----------------------------------------

if [ ! -d "$HOME/.oh-my-zsh/custom/plugins/fzf-tab" ]; then
  echo "➡️ Installing fzf-tab plugin..."
  git clone https://github.com/Aloxaf/fzf-tab "$HOME/.oh-my-zsh/custom/plugins/fzf-tab"
fi

#-----------------------------------------
# Install nvm
#-----------------------------------------

if [ ! -d "$HOME/.nvm" ]; then
  echo "➡️ Installing nvm..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh)"
fi

#-----------------------------------------
# Run macos bootstrap
#-----------------------------------------

if [ -e "$HOME/.config/macos/bootstrap.sh" ]; then
  echo "➡️ Setting up macos settings..."
  /bin/bash -c "$HOME/.config/macos/bootstrap.sh"
fi

#-----------------------------------------
# Start background apps
#-----------------------------------------

if [ -e "/Applications/1Password.app" ]; then
    open -a 1Password
fi

if [ -e "/Applications/Rectangle.app" ]; then
    open -a Rectangle
fi

#-----------------------------------------
# * Set yadm origin url to ssh
#-----------------------------------------

echo "➡️ Updating the yadm origin to ssh repo url..."
yadm remote set-url origin "$SSH_REPO_URL"

echo "🎉 Done (you may need to run \`source ~/.zshrc\` to get changes) 🎉"
